version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    reviewers:
      - 'mattietea'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    commit-message:
      prefix: feat
      prefix-development: chore
      include: scope
    reviewers:
      - 'mattietea'
